[package]
name = "midi-panel-meter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmidi = "4.0.6"
rpi-led-matrix = "0.4.0"